# Generated by Django 2.2 on 2019-05-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
