# Generated by Django 2.2 on 2019-05-22 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_visit_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_view_content', 'Can view content'),)},
        ),
    ]
