# Generated by Django 2.2 on 2019-05-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190523_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_edit_content', 'Can edit content'),)},
        ),
    ]
